name: main
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
